<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBookingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bookings', function (Blueprint $table) {
            $table->unsignedBigInteger('contact_id')->nullable();
            $table->nullableTimestamps();
            $table->date('date');
            $table->softDeletes();
            $table->string('end', 20)->nullable();
            $table->increments('id');
            $table->string('meet_link', 255)->nullable();
            $table->json('metadata')->nullable();
            $table->tinyInteger('notified_2')->default(0);
            $table->tinyInteger('notified_24')->default(0);
            $table->unsignedBigInteger('service_id');
            $table->string('start', 20)->nullable();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->string('zoom_link', 255)->nullable()->collation('utf8mb4_bin')->default('');
            $table->index('user_id', 'user_id');
            $table->index('service_id', 'service_id');
            $table->index('contact_id', 'contact_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('bookings');
    }
}
