<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateChatbotsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('chatbots', function (Blueprint $table) {
            $table->string('bot_id', 100)->default('');
            $table->nullableTimestamps();
            $table->string('description', 255)->nullable()->default('');
            $table->bigIncrements('id');
            $table->tinyInteger('is_start')->default(0);
            $table->string('title', 255)->default('');
            $table->unsignedBigInteger('user_id');
            $table->index('user_id', 'user_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('chatbots');
    }
}
