<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePendingInvoicesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pending_invoices', function (Blueprint $table) {
            $table->integer('amount');
            $table->unsignedBigInteger('contact_id');
            $table->nullableTimestamps();
            $table->increments('id');
            $table->json('service_ids');
            $table->unsignedBigInteger('user_id');
            $table->index('user_id', 'user_id');
            $table->index('contact_id', 'contact_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pending_invoices');
    }
}
