<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMessagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('messages', function (Blueprint $table) {
            $table->unsignedBigInteger('conversation_id')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->bigIncrements('id');
            $table->tinyInteger('is_history')->default(0);
            $table->tinyInteger('is_read')->default(0);
            $table->longText('link_preview')->nullable();
            $table->longText('message')->nullable();
            $table->json('metadata')->nullable();
            $table->longText('preview')->nullable();
            $table->string('source', 255)->nullable()->default('');
            $table->json('tags')->nullable();
            $table->string('timestamp', 191)->nullable();
            $table->enum('type', ['text', 'emoji', 'image', 'audio', 'video', 'file', 'call_failed', 'call_ended'])->default('text');
            $table->unsignedBigInteger('user_id')->nullable();
            $table->index('user_id', 'user_id');
            $table->index('conversation_id', 'convo_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('messages');
    }
}
