<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateContactsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('contacts', function (Blueprint $table) {
            $table->json('blacklisted_services')->nullable();
            $table->unsignedBigInteger('contact_user_id')->nullable();
            $table->nullableTimestamps();
            $table->json('custom_fields')->nullable();
            $table->string('email', 191)->default('');
            $table->string('first_name', 191)->nullable();
            $table->bigIncrements('id');
            $table->string('invite_token', 30)->default('');
            $table->json('invoices')->nullable();
            $table->tinyInteger('is_pending')->default(1);
            $table->string('last_name', 191)->nullable();
            $table->string('stripe_customer_id', 191)->nullable();
            $table->json('subscriptions')->nullable();
            $table->unsignedBigInteger('user_id');
            $table->string('xero_guid', 191)->nullable();
            $table->index('user_id', 'user_id');
            $table->index('contact_user_id', 'customer_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('contacts');
    }
}
