<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePackagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('packages', function (Blueprint $table) {
            $table->nullableTimestamps();
            $table->softDeletes();
            $table->string('description', 255)->default('');
            $table->date('expiration_date');
            $table->bigIncrements('id');
            $table->tinyInteger('in_widget')->default(0);
            $table->tinyInteger('is_available')->default(1);
            $table->string('name', 191)->default('');
            $table->double('price', 11, 2);
            $table->json('services');
            $table->unsignedBigInteger('user_id');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('packages');
    }
}
