<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePendingSubscriptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pending_subscriptions', function (Blueprint $table) {
            $table->double('amount', 11, 2);
            $table->unsignedBigInteger('contact_id')->nullable();
            $table->nullableTimestamps();
            $table->date('date')->nullable();
            $table->integer('duration')->nullable();
            $table->enum('duration_frequency', ['month', 'year'])->nullable();
            $table->increments('id');
            $table->enum('recurring_frequency', ['week', 'month', 'year'])->nullable();
            $table->json('services');
            $table->unsignedBigInteger('user_id')->nullable();
            $table->index('user_id', 'user_id');
            $table->index('contact_id', 'contact_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_0900_ai_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pending_subscriptions');
    }
}
