<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateConversationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('conversations', function (Blueprint $table) {
            $table->json('archive_users')->nullable();
            $table->unsignedBigInteger('contact_id')->nullable();
            $table->nullableTimestamps();
            $table->json('custom_fields')->nullable();
            $table->softDeletes();
            $table->bigIncrements('id');
            $table->json('metadata')->nullable();
            $table->string('name', 191)->nullable()->charset('latin1')->collation('latin1_swedish_ci');
            $table->string('source', 100)->nullable()->charset('latin1')->collation('latin1_swedish_ci');
            $table->json('tags')->nullable();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->index('user_id', 'user_id');
            $table->index('contact_id', 'user_customer_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('conversations');
    }
}
